/// <mls fileReference="_102030_/l2/petShopStripe/web/desktop/page11/accountOrdersPage.defs.ts"  enhancement="_blank"/>
export const skill = `
## Pages spec
\`\`\`JSON
{"pageId":"accountOrdersPage","pageName":"Minha conta e pedidos","actor":"cliente","purpose":"Acompanhar hist\u00f3rico de compras, servi\u00e7os e status de pedidos.","capabilities":["manageCartCheckout","bookService"],"flowRefs":{"experienceFlows":[],"entityLifecycles":[],"taskWorkflows":["serviceBooking"],"automations":[]},"pluginRefs":[],"mdmRefs":["customer"],"pageInputs":[{"name":"orderStatus","type":"string","required":false,"sources":["queryParam"],"description":"Filtro opcional de status do pedido."},{"name":"bookingStatus","type":"string","required":false,"sources":["queryParam"],"description":"Filtro opcional de status do agendamento."},{"name":"startDate","type":"date","required":false,"sources":["queryParam"],"description":"Data inicial para filtrar hist\u00f3rico."},{"name":"endDate","type":"date","required":false,"sources":["queryParam"],"description":"Data final para filtrar hist\u00f3rico."}],"navigationRefs":[{"direction":"outbound","pageId":"productServiceDetailPage","trigger":"Repetir compra ou agendar servi\u00e7o"}],"sections":[{"sectionName":"filtrosDeHistorico","mode":"interactive","organisms":[{"organismName":"orderAndBookingFilters","purpose":"Permitir filtrar pedidos e agendamentos por per\u00edodo e status.","userActions":["Aplicar filtros","Limpar filtros"],"requiredEntities":[],"readsFields":[],"writesFields":[],"rulesApplied":[]}]},{"sectionName":"historicoDePedidos","mode":"read","organisms":[{"organismName":"orderHistoryList","purpose":"Listar pedidos do cliente com itens, valores e status de pagamento/entrega.","userActions":["Visualizar pedido","Repetir compra"],"requiredEntities":["Order","OrderItem","Payment"],"readsFields":["Order.order_id","Order.order_number","Order.status","Order.payment_status","Order.total_amount","Order.created_at","OrderItem","Payment.status"],"writesFields":[],"rulesApplied":[]}]},{"sectionName":"agendamentosDeServicos","mode":"read","organisms":[{"organismName":"serviceBookingList","purpose":"Exibir agendamentos do cliente com data/hora, pet e status.","userActions":["Ver detalhes do agendamento","Agendar novamente"],"requiredEntities":["ServiceBooking","Service","Pet"],"readsFields":["ServiceBooking.service_booking_id","ServiceBooking.status","ServiceBooking.scheduled_date","ServiceBooking.scheduled_start_time","ServiceBooking.scheduled_end_time","ServiceBooking.timezone","Service","Pet"],"writesFields":[],"rulesApplied":[]}]}]}
\`\`\`

## Base Class
\`\`\`JSON
    [[(_102030_/l2/petShopStripe/web/shared/accountOrdersPage.ts)]]
\`\`\`
`;
