/// <mls fileReference="_102030_/l2/petShopStripe/web/desktop/page11/adminCatalogPage.defs.ts"  enhancement="_blank"/>
export const skill = `
## Pages spec
\`\`\`JSON
{"pageId":"adminCatalogPage","pageName":"Administração de catálogo","actor":"adminPetShop","purpose":"Cadastrar, editar e desativar produtos, serviços e categorias.","capabilities":["manageCatalog"],"flowRefs":{"experienceFlows":[],"entityLifecycles":["catalogManagement"],"taskWorkflows":[],"automations":[]},"pluginRefs":[],"mdmRefs":["productService","organization"],"pageInputs":[{"name":"itemType","type":"string","required":false,"sources":["queryParam"],"description":"Tipo de item a administrar (produto, serviço ou categoria)."},{"name":"statusFilter","type":"string[]","required":false,"sources":["queryParam"],"description":"Filtro de status para itens do catálogo."}],"navigationRefs":[{"direction":"outbound","pageId":"adminDashboardPage","trigger":"Voltar ao dashboard"}],"sections":[{"sectionName":"Filtros e lista de catálogo","mode":"view","organisms":[{"organismName":"CatalogFilters","purpose":"Definir filtros de tipo, status e categoria para a lista administrativa.","userActions":["Aplicar filtros","Limpar filtros"],"requiredEntities":["Product","Service","CatalogCategory"],"readsFields":["Product.status","Product.categoryId","Service.status","Service.categoryId","CatalogCategory.id","CatalogCategory.name"],"writesFields":[],"rulesApplied":[]},{"organismName":"CatalogAdminList","purpose":"Exibir lista de itens do catálogo com status e ações rápidas.","userActions":["Selecionar item","Iniciar criação de item","Ativar/desativar item"],"requiredEntities":["Product","Service","CatalogCategory"],"readsFields":["Product.id","Product.name","Product.price","Product.status","Service.id","Service.name","Service.price","Service.status","CatalogCategory.id","CatalogCategory.name","CatalogCategory.status"],"writesFields":[],"rulesApplied":[]}]},{"sectionName":"Editor de item de catálogo","mode":"edit","organisms":[{"organismName":"CatalogItemForm","purpose":"Cadastrar ou editar dados do item selecionado do catálogo.","userActions":["Salvar item","Atualizar item","Desativar item"],"requiredEntities":["Product","Service","CatalogCategory"],"readsFields":["Product.id","Product.name","Product.description","Product.price","Product.status","Product.categoryId","Service.id","Service.name","Service.description","Service.price","Service.duration","Service.status","Service.categoryId","CatalogCategory.id","CatalogCategory.name","CatalogCategory.status"],"writesFields":["Product.name","Product.description","Product.price","Product.status","Product.categoryId","Service.name","Service.description","Service.price","Service.duration","Service.status","Service.categoryId","CatalogCategory.name","CatalogCategory.status"],"rulesApplied":[]}]}]}
\`\`\`

## Base Class
\`\`\`JSON
    [[(_102030_/l2/petShopStripe/web/shared/adminCatalogPage.ts)]]
\`\`\`
`;
