/// <mls fileReference="_102030_/l2/petShopStripe/web/desktop/page11/checkoutPage.defs.ts"  enhancement="_blank"/>
export const skill = `
## Pages spec
\`\`\`JSON
{"pageId":"checkoutPage","pageName":"Checkout","actor":"cliente","purpose":"Coletar dados finais e confirmar pagamento via Stripe.","capabilities":["manageCartCheckout","payWithStripe"],"flowRefs":{"experienceFlows":[],"entityLifecycles":["checkoutAndPayment"],"taskWorkflows":[],"automations":[]},"pluginRefs":["stripePaymentsPlugin"],"mdmRefs":["customer"],"pageInputs":[{"name":"cartId","type":"string","required":true,"sources":["previousStepResult","routeParam"],"description":"Identificador do carrinho confirmado para iniciar o checkout.","entityRef":"Cart","fieldRef":"cartId"}],"navigationRefs":[{"direction":"inbound","pageId":"cartPage","trigger":"Iniciar checkout"},{"direction":"outbound","pageId":"accountOrdersPage","trigger":"Pagamento confirmado","description":"Acompanhar pedido após confirmação do pagamento."}],"sections":[{"sectionName":"Resumo do pedido","mode":"view","organisms":[{"organismName":"checkoutCartSummary","purpose":"Exibir itens confirmados do carrinho e totais do pedido.","userActions":[],"requiredEntities":["Cart","CartItem","Product","Service"],"readsFields":["cart.items","cart.items.itemType","cart.items.productId","cart.items.serviceId","cart.items.name","cart.items.quantity","cart.items.unitPrice","cart.items.totalPrice","cart.totals.subtotal","cart.totals.discount","cart.totals.shipping","cart.totals.total","cart.currency"],"writesFields":[],"rulesApplied":[]}]},{"sectionName":"Dados de entrega e contato","mode":"edit","organisms":[{"organismName":"deliveryContactForm","purpose":"Coletar endereço de entrega e dados de contato do cliente.","userActions":["Informar endereço de entrega","Informar dados de contato"],"requiredEntities":["Address","Customer"],"readsFields":[],"writesFields":["order.deliveryAddress","order.contact"],"rulesApplied":[]}]},{"sectionName":"Pagamento Stripe","mode":"action","organisms":[{"organismName":"stripePaymentConfirmation","purpose":"Confirmar criação do pedido e executar pagamento via Stripe.","userActions":["Confirmar dados do pedido","Confirmar pagamento Stripe"],"requiredEntities":["Order","Payment","StripeTransaction"],"readsFields":["order.orderId","order.orderNumber","order.status","order.paymentStatus","order.totalAmount","order.currency"],"writesFields":["order.status","order.paymentStatus","payment.status","stripeTransaction.status"],"rulesApplied":["ruleOrderRequiresCustomer","rulePaymentRequiredToConfirmOrder","ruleStripeTransactionLink","ruleMetricsUpdateOnOrderPaid"]}]}]}
\`\`\`

## Base Class
\`\`\`JSON
    [[(_102030_/l2/petShopStripe/web/shared/checkoutPage.ts)]]
\`\`\`
`;
